name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
    - main
env:
  
  signTool: '"C:\\Program Files (x86)\\Windows Kits\\10\bin\\10.0.18362.0\\x86\\signtool.exe"'
  solutionFile: ContosoExpenses.sln
  projectFile: .\ContosoExpenses.Package\ContosoExpenses.Package.wapproj
  dotNetProject: .\ContosoExpenses\ContosoExpenses.csproj
  manifestPath: .\ContosoExpenses.Package\Package.appxmanifest
  # appInstallerUri: https://contosoexpensesgithub.z28.web.core.windows.net/
  appInstallerUri: https://gentle-sea-007a8f903.azurestaticapps.net/
  platform: x86
  configuration: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@2008f912f56e61277eefaac6d1888b750582aa16
  
    - name: Use Nerdbank.GitVersioning to set version variables
      uses: aarnott/nbgv@v0.3
      with:
        setAllVars: true
    
    - name: Update manifest version
      run: |
        [xml]$manifest = get-content ${{env.manifestPath}}
        $manifest.Package.Identity.Version = "${{env.NBGV_SimpleVersion}}.0"
        $manifest.save("${{env.manifestPath}}")
        
    - name: Restore packages
      run: dotnet restore ${{env.dotNetProject}}
  
    - name: Build
      run: msbuild ${{env.projectFile}} /p:Configuration=${{env.configuration}} /p:AppxBundlePlatforms=${{env.platform}} /p:AppxPackageDir=${{github.workspace}}\AppPackages /p:AppxBundle=Never /p:UapAppxPackageBuildMode=SideloadOnly /p:AppxPackageSigningEnabled=false /p:AppInstallerUri=${{env.appInstallerUri}}
    
    - name: Install AzureSignTool
      run: dotnet tool install --global AzureSignTool --version 2.0.17
        
    - name: Sign package
      run: |
            Get-ChildItem -recurse -Include *.msix | ForEach-Object {
            $msixPath = $_.FullName
            & AzureSignTool sign -kvu https://contosoexpenses.vault.azure.net/ -kvi "${{ secrets.AzureClientId }}" -kvs "${{ secrets.AzureClientSecret }}" -kvc MyCertificate -tr http://timestamp.digicert.com -v $msixPath
            }  

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: MSIX
        # Directory containing files to upload
        path: AppPackages
        
  deploy:
    needs: build
    name: Deploy Packages
    runs-on: ubuntu-latest
    steps:
      - name: Download Package artifact
        uses: actions/download-artifact@master
        with:
          name: MSIX
          path: MSIX 

      # - name: Azure Static Website
      #   uses: tibor19/static-website-deploy@v1
      #   with:
      #     # Connection String of the Azure Storage Container
      #     connection-string: ${{secrets.azureStorageConnectionString}}
      #     # Folder containing the files to be uploaded to the Storage Container
      #     folder: MSIX
      #     # Name of the Blob Container Storage
      #     blob-container-name: $web
      #     # Access Policy to update in the Container (BlobContainer | Blob | None). For private containers do not specity any value.
      #     enabled-static-website: true
      #     # Index file for the static website
      #     index-file: index.html
      #     # 404 Error file for the static website          

            

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_SEA_007A8F903 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig 
          app_location: 'MSIX' # App source code path
          # app_artifact_location: 'MSIX' # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
